spring.application.name=Backend

#Postgres Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:test}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/ecommerce

# Google Gemini Model configuration
spring.ai.google.genai.api-key=${gemini.api.key}
spring.ai.google.genai.chat.model=gemini-3.6-flash
spring.ai.google.genai.chat.options.model=gemini-3.6-flash

gemini.api.key=${GEMINI_API_KEY}

# JWT Security Configuration
jwt.secret=${JWT_SECRET:9a4f2c8d3b7a1e5f8c6b3a2d1e0f9c8b7a6d5c4b3a2e1d0f9c8b7a6d5c4b3a2e}
jwt.expiration=${JWT_EXPIRATION:86400000}